baseurl      = "https://ycyyo.github.io"
title        = "ycyyo's blog"
languageCode = "zh-tw"
theme        = "hello-friend-ng"
pagination.pagerSize     = 10
defaultContentLanguage = 'zh-tw'
hasCJKLanguage = true

[params]
  dateform        = "Feb 16, 2026"
  # dateformShort   = "Feb 16"
  dateformNum     = "2026-02-16"
  dateformNumTime = "2026-02-16 14:25"

  # Subtitle for home
  homeSubtitle = "還沒想好這裡要寫什麼"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "ycyyo's blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.zh-tw]
    title = "ycyyo's blog"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.zh-tw.params]
    [languages.zh-tw.params.logo]
      logoText = "Nice to Meet You"
      logoHomeLink = "/"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "exchange"
    name       = "交換生的蒙特婁生存指南"
    url        = "/exchange/"
    hasChildren = false

  [[menu.main]]
    identifier = "form"
    name       = "明信片許願池"
    url        = "https://docs.google.com/forms/d/e/1FAIpQLSdu8ODkXTnmL2CHhqLHlvKNJHZ_0fXz_27N5xi_B9vSMQUMqQ/viewform?usp=publish-editor"
    hasChildren = false