baseurl      = "https://ycyyo.github.io"
title        = "ycyyo's blog"
languageCode = "zh-tw"
theme        = "hello-friend-ng"
pagination.pagerSize     = 10
defaultContentLanguage = 'zh-tw'
hasCJKLanguage = true
googleAnalytics = 'G-2K1GVG0JE8'

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "🌠 努力成為一個會記錄生活的人"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "ycyyo's blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.zh-tw]
    languageName = "繁體中文"
    languageCode = "zh-TW"
    weight = 1
    title = "ycyyo's blog"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.zh-tw.params]
    homeSubtitle = "🌠 努力成為一個會記錄生活的人"

    [languages.zh-tw.params.logo]
      logoText = "Nice to Meet You"
      logoHomeLink = "/"

  [[languages.zh-tw.menu.main]]
    identifier = "02-travel"
    name       = "遊記們"
    hasChildren = true

  [[languages.zh-tw.menu.main]]
    identifier = "02-01-travel-toronto"
    name       = "20260228 多倫多之旅"
    parent     = "02-travel"
    url        = "/series/travel-toronto"
    hasChildren = false
    
  # And you can even create generic menu
  [[languages.zh-tw.menu.main]]
    identifier = "01-exchange"
    name       = "交換生的蒙特婁生存指南"
    url        = "/series/exchange"
    hasChildren = false

  [languages.en]
    languageName = "English"
    languageCode = "en-US"
    weight = 2
    title = "ycyyo's blog"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.en.params]
    homeSubtitle = "🌠 Trying to become someone who records life"

    [languages.en.params.logo]
      logoText = "Nice to Meet You"
      logoHomeLink = "/en/"

  [[languages.en.menu.main]]
    identifier = "02-travel"
    name       = "Trips"
    hasChildren = true

  [[languages.en.menu.main]]
    identifier = "02-01-travel-toronto"
    name       = "2026-02-28 Toronto Trip"
    parent     = "02-travel"
    url        = "/en/series/travel-toronto"
    hasChildren = false

  [[languages.en.menu.main]]
    identifier = "01-exchange"
    name       = "Poly Montreal Exchange Guide"
    url        = "/en/series/exchange"
    hasChildren = false
